### ISSUE TITLE
Duplicatas

### ISSUE THREAD

**Issue by luanvilarim** [RafaelCastaneda/sca2#20]
@RafaelCastaneda, estive tentando remover as duplicatas da classe Professor, porém não consigo. Se observar o código vai ver que eu coleto todas as linhas da tabela xls definida no código e jogo a lista de duplicatas num _HashSet_ para remoção das mesmas. Por algum motivo o _HashSet_ considera objetos idênticos de Professor (idênticos baseando-me no método _equals_) como diferentes e nunca os remove. Mesmo adicionando uma um no _Set_ não foi possível remover as duplicatas, mesmo preenchendo cada objeto duplicata com os mesmos dados eles sempre tem uma diferença que não é visível a nível de código e debug. Fiz algumas alterações que eram necessárias no código XLS de Professor e no modelo do mesmo. Mas não tive sucesso na remoção das duplicatas

**Comment by RafaelCastaneda** [comment]
Luã,

O hashset não usa o método equals, mas sim o método hashcode para
determinar igualdade, você pode gerar o método hashcode pela ide do eclipse
mesmo. Se ainda assim não der certo, pode entregar a tarefa como está que a
considerarei concluída, ok?

Pode avisar o Bernardo desta deliberação.

Abraços,

Castaneda

Em 7 de dez de 2017 11:23 PM, "luanvilarim" <notifications@github.com>
escreveu:

**Comment by luanvilarim** [comment]
Era isso mesmo. Dei override nos métodos equals e hashCode pois se for apenas em um vai continuar dando erro.
