### ISSUE TITLE
Backend: Clonar modules do sca 1.0 para sca 2.0

### ISSUE THREAD

**Issue by luanvilarim** [RafaelCastaneda/sca2#3]
@RafaelCastaneda, não temos acesso à versão antiga do sca pra reaproveitar o que foi demonstrado em aula.

**Comment by RafaelCastaneda** [comment]
É só pegar o zip que está na nossa pasta do Google drive. Mandei o link no
grupo

Em 30 de ago de 2017 7:25 PM, "luanvilarim" <notifications@github.com>
escreveu:

**Comment by luanvilarim** [comment]
Verdade, tinha esquecido.
