### ISSUE TITLE
Importar xls em Classes com relacionamento

### ISSUE THREAD

**Issue by luanvilarim** [RafaelCastaneda/sca2#6]
@RafaelCastaneda, estou com um problema. Quando vou importar classes como VersaoCurso, que necessitam de outra classe para serem construídas, como por exemplo, quando VersaoCurso necessita de Curso. 
Estou criando uma instância de CursoDaoXls dentro de VersaoCursoDaoXls para pegar os Cursos que são referentes á VersaoCurso que está sendo importada.  Acredito que o problema seja de contexto do JUnit que não dá inicializa o properties dentro de um classe encapsulada na outra. O que seria melhor: Mudar a forma com a qual eu pego infos necessárias para a const de classes ou mudar a forma com a qual o caminho é compartilhado?

Em ambos, não tenho idéia do que fazer...

**Comment by RafaelCastaneda** [comment]
Leva na próxima aula o problema que bolamos uma solução de arquitetura para
isso, blz?

Abração!

Em 17 de set de 2017 12:33 PM, "luanvilarim" <notifications@github.com>
escreveu:
